- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: "v0.9.1"
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: flake8
- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: "1.0.4"
  hooks:
    - id: python-import-sorter
      args: ['--silent-overwrite']
